set-option -g default-terminal "screen-256color"
set-option -g history-limit 10000
set-option -g display-time 5000
set-option -g repeat-time 1000
set-window-option -g display-panes-time 1500
set-option -g repeat-time 0
set-option -g renumber-windows on

# Set window notifications
setw -g monitor-activity on
set -g visual-activity on
bind R source-file ~/.tmux.conf \; display-message "Config reloaded.."

set -g mouse on
